name: on-pull-request

on:
    pull_request:
    push:
        branches:
            - 'master'

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'
            - name: Install dependencies
              run: npm ci
            - name: Check Formatting
              run: git fetch origin master && npm run format:check -- --base=origin/master
            - name: Integration Test (Jest)
              run: npm run test
            - name: Integration Test (Karma)
              run: npx nx run integration:test-karma
            - name: Build App
              run: npm run build -- --prod
            - name: Build Package
              run: npm run build-package
